apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: solar-system
  name: solar-system
  namespace: "_{_NAMESPACE_}_"
spec:
  selector:
    matchLabels:
      name: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        name: solar-system
    spec:
      containers:
      - image: "_{_IMAGE_}_"
        imagePullPolicy: Always
        name: solar-system
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        envFrom:
        - secretRef:
            name: mongo-db-creds
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "250Mi"
            cpu: "500m"