apiVersion: v1
kind: Secret
metadata:
  name: mongo-db-creds
  namespace: "_{_NAMESPACE_}_"
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: myuser
  MONGO_INITDB_ROOT_PASSWORD: mypassword
  MONGO_INITDB_DATABASE: superData
