apiVersion: v1
kind: Service
metadata:
  name: solar-system
  namespace: "_{_NAMESPACE_}_"
  labels:
    name: solar-system
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "classic"       
    service.beta.kubernetes.io/aws-load-balancer-internal: "false" 
spec:
  type: LoadBalancer
  selector:
    name: solar-system
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP