apiVersion: v1
kind: Service
metadata:
  name: solar-system
  namespace: "_{_NAMESPACE_}_"
  labels:
    name: solar-system
spec:
  selector:
    name: solar-system
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP