name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
env:
  MONGO_URI: ${{ vars.MONGO_URI }}    
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
    
jobs:
    unit-testing:
        name: Unit Testing
        services:
          mongo-db:
            image: siddharth67/mongo-db:non-prod
            ports:
              - 27017:27017
    
        env:
          MONGO_URI: 'mongodb://localhost:27017/superData'
          MONGO_USERNAME: non-prod-user
          MONGO_PASSWORD: non-prod-password
        strategy:
          matrix:
           nodejs_version: [18,20] 
           operating_systems: [ubuntu-latest]

        runs-on: ${{ matrix.operating_systems }}
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version - ${{ matrix.nodejs_version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{matrix.nodejs_version}}

        - name: Composite Action - Cache & Install NPM Packages
          uses: ./.github/workflows/custom-actions/npm-action
          with:
            path_of_folder: node_modules
                 
        - name: Unit Testing
          id: nodejs-unit_testing-step
          run: npm test
          
        - name: Archive Test Result
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: Mocha-Test-Result-${{ matrix.nodejs_version }}-${{ matrix.operating_systems }}-${{ github.run_number }}
            path: test-results.xml

    code-coverage:
        name: Code Coverage
        container: 
          image: node:18
        services:
          mongo-db:
            image: siddharth67/mongo-db:non-prod
            options: 
              --name mongo
        env:
          MONGO_URI: 'mongodb://mongo:27017/superData'    
          MONGO_USERNAME: non-prod-user
          MONGO_PASSWORD: non-prod-password           
        runs-on: ubuntu-latest

        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4

         # - name: Setup NodeJS Version - 18
         #   uses: actions/setup-node@v3
         #   with:
         #    node-version: 18

          - name: Composite Action - Cache & Install NPM Packages
            uses: ./.github/workflows/custom-actions/npm-action
            with:
             path_of_folder: node_modules

          - name: Check Code Coverage
            continue-on-error: true
            run: npm run coverage

          - name: Archive Test Result
            uses: actions/upload-artifact@v4
            with:
               name: Code-Coverage-Result
               path: coverage
               retention-days: 5

    reports-s3:
      needs: [unit-testing,code-coverage]  
      name: AWs S3 - Upload Artifact
      runs-on: ubuntu-latest
      continue-on-error: true
      steps:
        - name: Download Mocha Test Artifact   
          uses: actions/download-artifact@v4       
          with: 
            pattern: Mocha-Test-Result-*
            merge-multiple: true

        - name: Download Code Coverage Artifact   
          uses: actions/download-artifact@v4       
          with: 
            name: Code-Coverage-Result      
         
        - name: Merge Test files
          run: |
            ls -ltr
            mkdir reports-${{ github.sha }}    
            mv cobertura-coverage.xml reports-${{ github.sha }}/
            mv test-results.xml reports-${{ github.sha }}/
            ls -ltr reports-${{ github.sha }}/

        - name: Upload Report Folder as Artifact
          uses: actions/upload-artifact@v4
          with:
            name: merged-reports
            path: reports-${{ github.sha }}
    
        - name: Upload to AWS S3    
          run: echo "Uploading............................"
           

    docker:
       name: contaierization
       needs: [unit-testing, code-coverage]
       permissions: 
        packages: write
       runs-on: ubuntu-latest
       steps:
          - name: Checkout Repository
            uses: actions/checkout@v4

          - name: Dockerhub login
            uses: docker/login-action@v2.2.0
            with: 
              username: ${{vars.DOCKERHUB_USERNAME}}
              password: ${{secrets.DOCKERHUB_PASSWORD}}    

          # - name: GHCR login
          #   uses: docker/login-action@v2.2.0
          #   with: 
          #     registry: ghcr.io
          #     username: ${{github.repository_owner}}
          #     password: ${{secrets.GITHUB_TOKEN}}      
               
          - name: Docker Build For Testing
            uses: docker/build-push-action@v4
            with:
             context: .
             push: false
             tags: |
               adelelnimr/solar-systems:${{ github.sha }}
               
          - name: Docker Image Test
            run: |
              docker images
              docker run --name solar-systems-app -d \
              -p 3000:3000 \
              -e MONGO_URI=$MONGO_URI \
              -e MONGO_USERNAME=$MONGO_USERNAME \
              -e MONGO_PASSWORD=$MONGO_PASSWORD \
              adelelnimr/solar-systems:${{ github.sha }}
              export IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' solar-systems-app)
              echo $IP
              echo Testing Image URL using wget
              wget -q -O - 127.0.0.1:3000/live | grep live

          - name: Docker Registry Push
            uses: docker/build-push-action@v4
            with:
             context: .
             push: true
             tags: |
              adelelnimr/solar-systems:${{ github.sha }}

               
    dev-deploy:
      if: contains(github.ref,'feature/')
      needs: docker
      uses: ./.github/workflows/reuse-deployment.yml
      secrets: 
        k8s-kubeconfig: ${{ secrets.KUBECONFIG }}
        mongodb-password: ${{ secrets.MONGO_PASSWORD }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        mongodb_uri: ${{ vars.MONGO_URI }} 
        environment: development 
        k8s-manifest-dir: kubernetes/development/
        namespace: development
             
    Dev-integration-Testing:
      if: contains(github.ref,'feature/')
      name: Dev integration Testing    
      needs: dev-deploy
      runs-on: ubuntu-latest
      steps:
        - name: Test URL Output using CURL and JQ
          env:
            URL: ${{ needs.dev-deploy.outputs.application_url }}
          run: |
            echo $URL
            echo "---------------------------------------------------------------"    
            curl http://$URL/live -s -k | jq -r .status | grep -i live

    Prod-deploy:
     if: github.ref == 'refs/heads/main'
     needs: docker
     uses: ./.github/workflows/reuse-deployment.yml
     secrets: 
        k8s-kubeconfig: ${{ secrets.KUBECONFIG }}
        mongodb-password: ${{ secrets.MONGO_PASSWORD }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
     with:
        mongodb_uri: ${{ vars.MONGO_URI }} 
        environment: Production    
        k8s-manifest-dir: kubernetes/production/
        namespace: production

    Prod-integration-Testing:
      if: github.ref == 'refs/heads/main'
      name: Prod integration Testing    
      needs: Prod-deploy
      runs-on: ubuntu-latest
      steps:
        - name: Test URL Output using CURL and JQ
          env:
            URL: ${{  needs.Prod-deploy.outputs.application_url }}
          run: |
            echo $URL
            echo "---------------------------------------------------------------"    
            curl https://$URL/live -s -k | jq -r .status | grep -i live
           
    slackNotification:
      if: always()
      name: Slack Notification
      needs: [Dev-integration-Testing,Prod-integration-Testing]
      continue-on-error: true
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }} 
          SLACK_CHANNEL: github-actions-channel
          SLACK_COLOR: ${{ job.status }}    # or specific color like 'good' or  '#ff00ff'   
        #  SLACK_ICON: https://gitlab.com/sidd-harth/solar-system/-/raw/main/images/saturn.png
          SLACK_MESSAGE: |
            ':hammer_and_wrench: Triggered by ${{github.actor}}'
            :bar_chart: Monitoring Ready
            Grafana: ${{ env.GRAFANA_URL }}
          SLACK_TITLE: Information
 

    monitoring:
     name: Deploy Monitoring (Prometheus + Loki + Grafana)
     needs: docker
     runs-on: ubuntu-latest

     steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: us-east-1

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name solar-system-application --region us-east-1

      - name: Add Helm Repos
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo update

      - name: Create monitoring namespace
        run: |
          kubectl get ns monitoring || kubectl create ns monitoring

      - name: Deploy Prometheus + Grafana
        run: |
           helm upgrade --install monitoring prometheus-community/kube-prometheus-stack \
           -n monitoring \
           -f kubernetes/monitoring/grafana-values.yaml


      - name: Deploy Loki
        run: |
          helm upgrade --install loki grafana/loki-stack \
          -n monitoring \
          -f kubernetes/monitoring/loki-values.yaml

      - name: Wait for Grafana Deployment
        run: |
           kubectl -n monitoring rollout status deployment monitoring-grafana

      - name: Wait for Grafana LoadBalancer
        id: grafana-url
        run: |
          echo "Waiting for Grafana LoadBalancer URL..."
          for i in {1..30}; do
            GRAFANA_HOST=$(kubectl get svc monitoring-grafana \
              -n monitoring \
              -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')

            if [ -n "$GRAFANA_HOST" ]; then
              echo "Grafana LoadBalancer ready: $GRAFANA_HOST"
              echo "GRAFANA_URL=http://$GRAFANA_HOST" >> $GITHUB_ENV
              echo "GRAFANA_URL=http://$GRAFANA_HOST" >> $GITHUB_OUTPUT
              exit 0
            fi

          echo "Still waiting... ($i)"
          sleep 10
          done

          echo "âŒ Grafana LoadBalancer not ready after timeout"
      exit 1

      - name: Publish Grafana URL
        run: |
          echo "## ðŸ“Š Monitoring Dashboard" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Grafana URL:** [$GRAFANA_URL]($GRAFANA_URL)" >> $GITHUB_STEP_SUMMARY
          echo "- **Username:** admin" >> $GITHUB_STEP_SUMMARY
          echo "- **Password:** (from secret)" >> $GITHUB_STEP_SUMMARY
  

